import type { TemplateDefinition } from '../types';

export const DEMO_TEMPLATES: TemplateDefinition[] = [
  {
    id: 'template-inmobiliario',
    name: 'Cartel Inmobiliario (Se Vende)',
    category: 'Inmobiliaria',
    description: 'Diseño clásico de alta visibilidad para venta o alquiler de propiedades.',
    design: {
      version: 1,
      id: 'design-inmobiliario-demo',
      name: 'Cartel Se Vende 100x70',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      productConfiguration: {
        productId: 'cartel-pvc',
        widthCm: 100,
        heightCm: 70,
        materialId: 'pvc-5mm',
        printMethodId: 'uv-color',
        finishId: 'laminado-mate',
        quantity: 2,
      },
      canvasElements: [
        {
          id: 'text-vende',
          type: 'text',
          text: 'SE VENDE',
          x: 50,
          y: 15,
          width: 90,
          height: 15,
          fontSize: 48,
          fontFamily: 'Inter',
          fill: '#1E293B',
          align: 'center',
          bold: true,
          rotation: 0,
          zIndex: 1,
        },
        {
          id: 'text-specs',
          type: 'text',
          text: '3 DORMITORIOS  •  2 BAÑOS  •  GARAGE',
          x: 50,
          y: 35,
          width: 90,
          height: 8,
          fontSize: 20,
          fontFamily: 'Inter',
          fill: '#334155',
          align: 'center',
          bold: true,
          rotation: 0,
          zIndex: 2,
        },
        {
          id: 'text-contact',
          type: 'text',
          text: 'CONSULTAS: 0800-555-1234',
          x: 50,
          y: 52,
          width: 90,
          height: 10,
          fontSize: 28,
          fontFamily: 'Inter',
          fill: '#2563EB',
          align: 'center',
          bold: true,
          rotation: 0,
          zIndex: 3,
        },
      ],
    },
  },
  {
    id: 'template-obra',
    name: 'Cartel Cartelería de Obra',
    category: 'Construcción',
    description: 'Cartel profesional con datos de permiso de obra, arquitecto y constructora.',
    design: {
      version: 1,
      id: 'design-obra-demo',
      name: 'Cartel de Obra 200x100',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      productConfiguration: {
        productId: 'cartel-pvc',
        widthCm: 200,
        heightCm: 100,
        materialId: 'pvc-5mm',
        printMethodId: 'uv-color',
        finishId: 'laminado-mate',
        quantity: 1,
      },
      canvasElements: [
        {
          id: 'text-title',
          type: 'text',
          text: 'ESTUDIO DE ARQUITECTURA & CONSTRUCCIONES',
          x: 100,
          y: 15,
          width: 180,
          height: 15,
          fontSize: 42,
          fontFamily: 'Inter',
          fill: '#0F172A',
          align: 'center',
          bold: true,
          rotation: 0,
          zIndex: 1,
        },
        {
          id: 'text-details',
          type: 'text',
          text: 'OBRA: Edificio Residencial Lumina\nEXPEDIENTE: EXP-2026-98412\nDIRECTOR DE OBRA: Arq. M. Rodríguez (MP 4512)\nEMPRESA CONSTRUCTORA: IAtomica Build S.A.',
          x: 100,
          y: 65,
          width: 180,
          height: 35,
          fontSize: 24,
          fontFamily: 'Inter',
          fill: '#1E293B',
          align: 'center',
          bold: false,
          rotation: 0,
          zIndex: 2,
        },
      ],
    },
  },
  {
    id: 'template-comercio',
    name: 'Promoción Comercio / Gran Apertura',
    category: 'Comercial',
    description: 'Diseño impactante para marquesina o vitrina de gran impacto visual.',
    design: {
      version: 1,
      id: 'design-comercio-demo',
      name: 'Gran Apertura 150x80',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      productConfiguration: {
        productId: 'cartel-pvc',
        widthCm: 150,
        heightCm: 80,
        materialId: 'pvc-5mm',
        printMethodId: 'uv-color',
        finishId: 'laminado-brillante',
        quantity: 1,
      },
      canvasElements: [
        {
          id: 'text-apertura',
          type: 'text',
          text: '¡GRAN APERTURA!',
          x: 75,
          y: 30,
          width: 90,
          height: 15,
          fontSize: 52,
          fontFamily: 'Inter',
          fill: '#2563EB',
          align: 'center',
          bold: true,
          rotation: 0,
          zIndex: 1,
        },
        {
          id: 'text-sub',
          type: 'text',
          text: 'DESCUENTOS EXCLUSIVOS HASTA 50% OFF',
          x: 75,
          y: 50,
          width: 90,
          height: 10,
          fontSize: 22,
          fontFamily: 'Inter',
          fill: '#D97706',
          align: 'center',
          bold: true,
          rotation: 0,
          zIndex: 2,
        },
      ],
    },
  },
];
